AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  ProjectName:
    Type: String
    Description: "Name of the project"
    Default: hephaestus

Description: >
  Hephaestus Business Logic Layer

Resources:
  LambdasBusinessLogicLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: !Sub "${ProjectName}"
      Description: "Hephaestus Business Logic Layer"
      ContentUri: ./
      CompatibleRuntimes:
        - python3.10
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

Outputs:

  DependenciesLayerV5:
    Description: "Hephaestus Business Logic Layer with version 5"
    Value: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${ProjectName}:5"
    Export:
        Name: !Sub "${ProjectName}-v5"
  DependenciesLayerV6:
    Description: "Hephaestus Business Logic Layer with version 6"
    Value: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${ProjectName}:6"
    Export:
      Name: !Sub "${ProjectName}-v6"
  DependenciesLayerV7:
    Description: "Hephaestus Business Logic Layer with version 7"
    Value: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${ProjectName}:7"
    Export:
      Name: !Sub "${ProjectName}-v7"
  DependenciesLayerV8:
    Description: "Hephaestus Business Logic Layer with version 8"
    Value: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${ProjectName}:8"
    Export:
      Name: !Sub "${ProjectName}-v8"
  DependenciesLayerV9:
    Description: "Hephaestus Business Logic Layer with version 9"
    Value: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${ProjectName}:9"
    Export:
      Name: !Sub "${ProjectName}-v9"
