AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  ProjectName:
    Type: String
    Description: "Name of the project"
    Default: atlas-crafter

Description: >
  Hephaestus Business Logic Layer

Resources:
  LambdasBusinessLogicLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: !Sub "${ProjectName}-business-logic-${ENV}"
      Description: "Hephaestus Business Logic Layer"
      ContentUri: ./
      CompatibleRuntimes:
        - python3.10
      LicenseInfo: "MIT"
      RetentionPolicy: Delete

Outputs:
  BusinessLogicDependeciesLayer:
    Description: "Hephaestus Business Logic Layer"
    Value: !Ref LambdasBusinessLogicLayer
    Export:
      Name: !Sub "${ProjectName}"
